author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

load: POSTWORLD

commands:
  R2G2:
    description: Debug/Test command
    usage: |
      /<command> <getIG|getTowel|getR2G2>
